kernel/cfs.c, kernel/lcfs-reader.c, kernel/lcfs-reader.h, kernel/lcfs.h, tools/dump.c, tools/lcfs/lcfs-writer.c, tools/lcfs/lcfs.h
This changes the main format of the descriptor. It is now
in two parts, the first is the inode data table which statrts
(with the root inode) directly after the header. This contains
an array lcfs_inode_s, each optionally followed by the payload of that
inode which is either lcfs_backing_s, lcfs_dir_s, or a symlink target.
The second part is a variable data accesses with vdata like before,
but now only used by xattrs. The size of the inode table is in the
header so we can know where the variable data starts.
With these changes the descriptor size for my testcase goes from 3.3Mb
to 3.0Mb.
Some other changes as part of this:
Inode order is more sane, its stored in breadth-first from the root.
The vdata are now indexed only by 32bit, as we're unlikely to need
more than 4GB of xattrs.
link …
=> Change file format layout

kernel/cfs.c, kernel/lcfs-reader.c, kernel/lcfs-reader.h, kernel/lcfs.h, tools/dump.c, tools/lcfs/lcfs-writer.c, tools/lcfs/lcfs.h
This makes the inode nr handling simple (its just the offset from the header), and it make the flags more flexible.
Since we now have more space for flags we can also add stuff, like for payloads and xattrs making these save space when missing. We also add a DIGEST_FROM_PAYLOAD flag that avoids storing the digest separately if it is encoded in the payload anyway.
=> Move inode flags inline with the inode data and add various flags

kernel/cfs.c, kernel/lcfs-reader.c, kernel/lcfs.h, tools/lcfs/lcfs-writer.c, tools/lcfs/lcfs.h
This ia a "more random" value, plus we can use it for sniffing and
quick validation. This replaces the inode_size in the header because
we don't really use that anywmore.
=> Use a better magic value and embed it in the descriptor header

kernel/cfs.c, kernel/lcfs-reader.c
a couple of issues that caused a segfault with the wrong metadata.
=> fix a couple of issues

kernel/lcfs.h
=> kernel: Drop use of uintN_t in favour of uN types

kernel/Makefile, kernel/cfs.c, kernel/lcfs-verity.h
it was used as an experiment to embed composefs inside the overlayfs
driver itself.
=> src: drop STANDALONE_COMPOSEFS define

libcomposefs/Makefile-lib.am, libcomposefs/Makefile.am
This can be used for e.g. ostree
=> Split out the libcomposefs Makefile to make it usable as a git submodule

kernel/lcfs-reader.c
We disallow embedded nuls or slashes, empty names, ".", and "..".
=> cfs: Validate filenames in directories

configure.ac, libcomposefs/Makefile-lib.am, libcomposefs/lcfs-fsverity.c, libcomposefs/lcfs-fsverity.h, libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, tools/Makefile.am, tools/mkcomposefs.c, tools/writer-json.c
This uses a custom fsverity hash implementation to allow us to compute the digest while writing the descriptor. And some cleanups.
=> Fsverity rework

tools/mkcomposefs.c
=> tools: mkcomposefs supports absolute dir as argument

configure.ac, libcomposefs/lcfs-fsverity.c, tools/mkcomposefs.c
This adds a fallback implementation of sha256, based on the glib code in case openssl is not used. This is primarily useful to make it easy to include the library as a git-submodule. For example, for non-openssl builds of ostree.
=> Make openssl dependency optional

fuzzing/main.c, kernel/Documentation/filesystems/composefs.rst, kernel/cfs-reader.c, kernel/cfs-reader.h, kernel/cfs.c, kernel/cfs.h, libcomposefs/lcfs-writer.c, libcomposefs/lcfs.h, tools/dump.c
This limits the xattr data size to 4k, and splits the dentry data into chunks of (max) 4k which we read in chunks as needed. This drops the in-memory requirement for inodes a lot.
@rhvgoyal does this take care of your issues wrt memory use?
Note: For memory use I will also look at re-using xattr chunks in memory between inodes as they are already shared on disk. Should be rather easy.
=> Limit in-memory use for inodes

kernel/cfs-internals.h, kernel/cfs-reader.c, kernel/cfs.c
This has some cleanup, and then switches the xattr code to directly use memory from the page cache. This means we don't have to copy this memory for each inode, slimming memory use and sharing memory for caching de-duplicated xattr data.
=> Use page cache for xattrs

kernel/cfs-internals.h, kernel/cfs-reader.c, kernel/cfs.c, kernel/cfs.h
With this series I now get:
```
$ checkpatch.pl --file cfs.c --file cfs-reader.c --file cfs.h --file cfs-internals.h
-----
cfs.c
-----
WARNING: LINUX_VERSION_CODE should be avoided, code should be for the version to which it is merged
#350: FILE: cfs.c:350:
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 18, 0))
WARNING: Comparisons should place the constant on the right side of the test
#350: FILE: cfs.c:350:
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 18, 0))
total: 0 errors, 2 warnings, 923 lines checked
NOTE: For some of the reported defects, checkpatch may be able to
mechanically convert to the typical style using --fix or --fix-inplace.
cfs.c has style problems, please review.
------------
cfs-reader.c
------------
total: 0 errors, 0 warnings, 961 lines checked
cfs-reader.c has no …
```
=> Fix warnings reported by checkpatch

kernel/cfs-reader.c
We can use read_cache_page() directly, which means this code works for older kernels without folios. We don't care about the folio anyway, so this just means less code.
=> kernel: Don't unnecessarily use folios

libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, tools/mkcomposefs.c
Without this it was a pain to figure out why mkcomposefs failed.
Also, this drops the unused "parent" arg to lcfs_build().
=> lib: Report error path in lcfs_build()

kernel/cfs-reader.c
Empty files have zero payload length, and no path, so the check for loading the poayload path should be payload_length > 0, not >= 0.
=> kernel: Fix stating empty files

kernel/cfs.c
=> kernel: Escape option strings in cfs_show_options()

kernel/cfs.c
prefer kern_unmount_array over kern_unmount since it uses internally synchronize_rcu_expedited that is faster than synchronize_rcu.
=> cfs: use kern_unmount_array

README.md, kernel/Documentation/filesystems/composefs.rst, kernel/cfs.c
This changes when we verify fs-verity. The goal is to have it easy to create fs-verity enabled images with `mkcomposefs --digest-store=`, but also make it easy to consume them without requiring you to explicitly disable verity.
The new setup is a single option verity_check=[0,1,2]. 0 means we never require verity. 1 means we veritfy backing file fs-verity if the image specifies a verity digest. 2 additionally means we require the image to specify a digest for all non-empty files.
Fixes https://github.com/containers/composefs/issues/74
=> Change when we require fs-verity

kernel/cfs.c
This drops the implicit handling of a rootdir as a basedir, as this behaviour can be unexpected to users. If you really want to use rootfs as basedir you can still explicitly list `/` in the basedir option.
=> Drop the implicit `/` basedir

tools/mkcomposefs.c
Maybe the fix is not this simple?
Closes: https://github.com/containers/composefs/issues/85
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>
=> mkcomposefs: handle fill_payload() error

kernel/Documentation/filesystems/composefs.rst, kernel/cfs-internals.h, kernel/cfs-reader.c, kernel/cfs.c, kernel/cfs.h, libcomposefs/lcfs-writer.c, libcomposefs/lcfs.h, tools/dump.c
This follows the discussion with dave chinner on the list. The descriptors are slightly larger (around 40%) but the format, as well as the code is much simpler and more performance.
We also drop the chunking of dirents in favour of using multi-page mappings (using vm_map_ram()) when reading the data from the page cache.,
This also adds various comments describing the file format in the header and generally fixes issues pointed out in the reviews.
=> Change to a simpler fixed size inode format

kernel/cfs-reader.c, kernel/cfs.c, libcomposefs/lcfs-writer.c
Use i_size_write to set i_size, and also call inode_set_bytes() to set i_blocks and i_bytes.
Drop the use of simple_get/setattr. These are just confusing as they overwrite i_blocks. The default generic_fillattrs work fine for us.
Also, don't randomly hardcode st_size for dirs, just follow whatever the inode data says, for simplicity.
=> Correctly handle sizes

kernel/cfs.h, libcomposefs/lcfs.h
This puts back the packed attributes on the on-disk struct, because otherwise we get a lot of holes in them, making things larger. We also add some "unused" padding to make the various structures fully or partially cacheline aligned.
=> Fix on-disk struct sizes

kernel/cfs-internals.h
=> kernel: Drop root_inode from cfs_context

kernel/cfs.c
=> kernel: add warning if no basedir was specified

kernel/cfs-reader.c
The binary search was handling the case of looking up something before the table, because when the lookup at start=0 end=0 (mid=0) fails, end was set to mid - 1, which is negative, so still passes the loop check for start_dirent <= end_dirent.
=> kernel: Fix binary search bounds check

kernel/cfs.c
This simplifies the code a bit, and is I believe equivalent.
=> kernel: Simplify cfs_read_iter by using vfs_iter_read()

hacking/clang-format/Makefile, kernel/cfs.c, libcomposefs/erofs_fs.h, libcomposefs/erofs_fs_wrapper.h, libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, tools/mkcomposefs.c
This adds support for --format=erofs to generate an erofs image designed to be used in combination with overlayfs.
=> Initial work on erofs support in mkcomposefs

libcomposefs/lcfs-writer.c
These are large and need only be read at open time, so moving them
out of line makes the inline inodes smaller and more efficient.
=> Don't inline overlay.digest xattr

libcomposefs/Makefile-lib.am, libcomposefs/lcfs-mount.c, libcomposefs/lcfs-mount.h, libcomposefs/lcfs-writer.c, tools/Makefile.am, tools/mountcomposefs.c
This moves the code to mount erofs+overlayfs images into the libcomposefs so that others can easily use it. It also changes mountcomposefs to /sbin/mount.composefs with a CLI that matches /bin/mount, which allows mount to use it as a helper, like so:
```
$ mount -t composefs -obasedir=objects simple.erofs mnt
```
=> Create mount.composefs helper

libcomposefs/lcfs-mount.c, libcomposefs/lcfs-mount.h, tools/mountcomposefs.c
This works by using the build-in fs-verity signatures and the kernel keyring. When you open any file that has fs-verity enabled with a signature the kernel verifies its signature against the keys in the kernel .fs-verity keyring. If the required key is not in the keychain then open will fail.
So, to work with this we just ensure that the file is open (i.e. we have an fd to it), it has fs-verity enabled, and there is a signature for the file. If this is all true we must have the valid key in the keyring.
To test this, do something like this:
Generate keys and sign image:
```
openssl req -newkey rsa:4096 -nodes -keyout key.pem -x509 -out cert.pem
fsverity sign image.composefs image.composefs.sig --key=key.pem --cert=cert.pem
```
Load the certificate into the fs-verity keyring:
```
openssl …
```
=> mount: Add support for validating fs-verity signatures on images.

composefs.spec.in, configure.ac, tools/Makefile.am, tools/mkcomposefs.c
We don't currently use it other than to enable fs-verity, which really is just a single ioctl call. So, lets call that directly instead.
=> Drop libsfverity dependency

libcomposefs/lcfs-mount.c
We're probing if "::" works, so maybe this will produce less spew.
=> mount: Pass MS_SILENT on first pass trying to mount overlayfs

libcomposefs/lcfs-mount.c, libcomposefs/lcfs-mount.h
Otherwise the random tmpdir will be encoded in the mount options. We want to use this in ostree so we can find the deploy dir from the root (overlay) mount.
=> lib: Add option for specifying the mountpoint for the erofs image

libcomposefs/lcfs-writer-erofs.c
This is changing upstream in the overlay patchset.
=> erofs: Store the overlay.verity xattr

libcomposefs/lcfs-mount.c, tools/composefs-from-json.c, tools/dump.c, tools/mkcomposefs.c, tools/mountcomposefs.c, tools/read-file.c
tree-wide: Use O_CLOEXEC
This is just a best practice.
---
tree-wide: Use fopen(..., "e")
This maps to `O_CLOEXEC`.
---
=> tree-wide: Use O_CLOEXEC

tools/mountcomposefs.c
Since the basedir option is actually required, let's add it to the help text.
Also support `-h` to be a bit friendlier.
=> mountcomposefs: Support -h and add an example output

.gitignore, hacking/clang-format/Makefile
gitignore: Only ignore automake-generated Makefiles
Otherwise `hacking/clang-format/Makefile` doesn't show up
in my searches.
---
hacking: use `grep -E`
To avoid a deprecation warning from `egrep`.
---
=> Two minor buildsys patches

libcomposefs/lcfs-mount.c, tools/dump.c, tools/mkcomposefs.c
lcfs-mount: Use `cleanup_free`
On general principle of avoiding memory leaks and double frees
by having deallocation happen automatically.
---
tools: Use `cleanup_free`
On general principle of avoiding memory leaks and double frees
by having deallocation happen automatically.
---
=> Use `cleanup_free` more

libcomposefs/lcfs-writer.c
I was testing out composefs with `-fsanitize=address`.  I highly recommend this as it's cheap and will absolutely find bugs.
In this case, what is happening here is that it's allowed for an initially `listxattr` call to return a larger size than the *real* size.  So we must take the second return value as the actual size.
Concretely in my setup, the initial `listxattr` call returns 40, but the second one returns 17.  With the current code, we just walk off the end of what was written by the Linux kernel and start reading uninitialized heap memory, which is caught by `-fsanitize=address`.
=> writer: Fix uninitialized read with xattrs

.github/workflows/test.yaml, hacking/installdeps.sh, tests/integration.sh
Right now we only have unit tests that run unprivileged.  Add a proper "integration test" (ok it's a lame shell script) that runs as root and creates and mounts a composefs and does some sanity checking.  (This could obviously be greatly extended, this is just to have a starting point)
While we have the patient open
- The only CI tests were doing *cross* builds; i.e. we were ignoring x86_64.  Add a non-cross build, and capture its result (as a tarball) for integration testing
- Add `hacking/installdeps.sh` which captures our build dependencies for Debian at least and can be reused by mutiple jobs
- Add `permissions: actions: read` because we don't want our actions to be able to mutate anything - this makes untrusted PRs much safer
=> ci: Add integration testing, misc cleanup

libcomposefs/lcfs-mount.c
The final merged variant of datalowers uses double-colon for every datalower directory, not just the first. I.e:
-o lower1:lower2::lowerdata1::lowerdata2.
=> mount: Use the new syntax for overlayfs datalower dirs

libcomposefs/.gitignore
ostree uses composefs as a git submodule today; this is what we do in libglnx too.
=> gitignore: Add `Makefile-*.am.inc`

libcomposefs/lcfs-writer-erofs.c
In the latest iteration of the overlay-verity patchset we changed from using the IMA algorithm enum (HASH_ALGO_SHA256) to the fs-verity specific one (FS_VERITY_HASH_ALG_SHA256).
=> Update to use the new hash-algorithm enum

libcomposefs/lcfs-mount.c, libcomposefs/lcfs-mount.h, tools/mountcomposefs.c
As discussed in #151, we may want to use other signatures than the fs-verity ones, and at some point other digests too. So, be more explicit in the naming that we refer to specifically fsverity digests and fsverity signatures.
=> library: Be more explicit about what kind of signatures/digest we mean

configure.ac, hacking/installdeps.sh, tools/Makefile.am, tools/cfs-fuse.c
This is a highly efficient implementation of the parts of erofs that we use in composefs.
With this performance of ls -lR of a fuse mount like this is broadly similar to that of a kernel filesystem, except it works rootless. It is stateless in that all it does is mmap the filesystem image and each fuse request is served directly from this mapping.
It does remap the trusted.overlay.* xattrs to user.overlay.*, with the goal of using this with overlayfs, but unfortunately that requires the user of the overlayfs mount option userxattr, which is incompatilble with redirects and metacopy, so this doesn't work atm.
We could perhaps fix that. Alternative approaches is to make it do the reads itself, but then we don't get the page-sharing aspects. One way to fix that is if we ever get the "fuse …
=> WIP Initial version of cfs-fuse

README.md
Goals:
- Clarify what composefs is today: a combination of underlying parts
- Even more strongly emphasize a key differentiator here in the page cache sharing
- Add more hyperlinks to external things
=> README.md: Rewrite intro and explanation

tests/integration.sh, tools/mkcomposefs.c
In some cases, it's very useful to just see what the composefs digest of an input tree is, without actually writing an image.  One could do this externally by allocating a tempfile, but it's nicer for us to do internally.
Here we allocate an anonymous `O_TMPFILE` and hence none of the written data will ever persist to disk.
=> mkcomposefs: Add --print-digest-only

libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h
In general our use case is really constructing an entire filesystem
tree in one shot from external data; we don't have a use case for
dynamic mutations, which is what this function does.
---
=> lcfs: Drop function to remove child

libcomposefs/lcfs-internal.h, libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, tools/composefs-from-json.c
As discussed in https://github.com/containers/storage/pull/1646 there is no support in EROFS for ctime != mtime.  The current code does nothing with it.
Drop support for it in the API.
=> Drop support for ctime

libcomposefs/lcfs-writer.c
This is UB, though I think glibc is resilient to it. Detected by running with `-fsanitizer=undefined`.
=> lib: Don't `qsort(NULL)`

libcomposefs/lcfs-mount.c, tools/mountcomposefs.c
This ensures we get a clean `-fsanitize=address` run.
=> mount: Fix two memory leaks

.github/workflows/test.yaml
Depends:
- #160 
- #159 
These are cheap enough and valuable enough that we should really run with them on by default in CI.
=> ci: Enable sanitiziers by default

tools/composefs-from-json.c
solves a problem where a path like "sys/" would cause to add a node with an empty name.
=> composefs-from-json: skip empty dir components

libcomposefs/lcfs-writer-erofs.c
This was spotted by gcc `-fanalyzer`.
=> lib: Add an unref in an error path

libcomposefs/lcfs-mount.c
Check the result from escape_mount_option() because the function might return NULL.
=> mount: fix missing check after calling escape_mount_option()

libcomposefs/lcfs-writer.c
I tried to fix some missing error return value checks.
=> writer: Fix missing error return value checks

libcomposefs/lcfs-writer.c, tools/mkcomposefs.c
writer: Drop dead assignment
Spotted by clang-analyzer.
---
mkcomposefs: Silence an unused variable warning
clang-analyzer complains about this.  While we're here, make
the variable `const`.
---
mkcomposefs: Switch to declare-and-initialize to silence clang-analyzer
clang-analyzer complains about a leak; I think it's wrong, but changing
things to atomically initialize the variables silences it.
---
mkcomposefs: Fix possibly garbage return in error path
Found by clang-analyzer.
(At this point, I have to say: I don't understand why in 2021 we
created a new project in the C programming language...)
---
=> A few smaller/more obvious fixes from running `clang-analyzer`

tools/cfs-fuse.c, tools/mountcomposefs.c
This tells the compiler and static analyzers that we exit; in this case clang-analyzer was warning about a possible `NULL` deref in `mountcomposefs.c` that wasn't reachable.
That said, this function is the same thing as `errx`, but we can fix that as a followup.
=> Use `noreturn` attribute for `printexit`

libcomposefs/lcfs-internal.h
required for htole16 and friends  
----
fixes a build with clang16 against musl:  
```
In file included from ../composefs/libcomposefs/lcfs-writer.c:21:
../composefs/libcomposefs/lcfs-internal.h:35:9: error: call to undeclared function 'htole16'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
return htole16(val);
```
this is because clang16 no longer permits using functions without a prototype first (implicit-decl)
=> lib: include endian.h for lcfs-internal.h

libcomposefs/lcfs-internal.h, libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c
This escapes overlayfs xattrs and whiteouts according to the support in this patch series:
https://lore.kernel.org/linux-unionfs/cover.1692198910.git.alexl@redhat.com/
Note: We should probably wait with merging this until we have more feedback on the kernel list about it.
Fixes  https://github.com/containers/composefs/issues/172
=> erofs: Escape overlayfs features

libcomposefs/lcfs-internal.h, libcomposefs/lcfs-utils.h, libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, tests/dumpdir, tests/integration.sh, tools/mkcomposefs.c
Some files are smaller than the size needed for the redirect and the digest, lets allow storing these inline instead.
=> Inline small files

tools/composefs-from-json.c
skip the path component when it is a single dot, since it refers to the current directory.
=> composefs-from-json: skip path component "."

tools/composefs-info.c
* Free memory when done.
* Add NULL check for calloc result.
=> composefs-info: Fix memory handling for calloc

.github/workflows/test.yaml, .gitignore, hacking/installdeps.sh, libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, tests/Makefile.am, tests/dumpdir, tests/gendir, tests/test-checksums.sh, tests/test-lib.sh, tests/test-random-fuse.sh, tests/test-units.sh, tools/.gitignore, tools/cfs-fuse.c, tools/mkcomposefs.c
This adds some fusa/tools tweaks and then some initial work on randomized image testing.
For now it only uses fuse so we can run this during unit tests, but I want to follow up with similar integration tests that do an actual kernel mount.
=> More tests

libcomposefs/lcfs-internal.h, libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c
This makes it easy to detect accidental cases where you get this wrong, and make it more explicit where we're casting to a different size.
=> Add static asserts that endian conversions are of right size

libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h
This moves some code from mkcomposefs to lcfs_build() to:
* Create by-digest payloads
* Create symlink payloads
And then uses it
It also simplifies the mkcomposefs arguments to always compute digest and by-digest payloads, dropping the --absolute option and related things, as we couldn't think of a usecase for it right now. If we have a more precise usecase later we can add it back in a way that makes sense for the usecase.
=> Simplify mkcomposefs

libcomposefs/lcfs-internal.h
Compiler reported errors as:
./lcfs-internal.h:65:47: error: expected ‘,’ before ‘)’ token
_Static_assert(sizeof(v) == sizeof(uint16_t));                 \
^
./lcfs-internal.h:71:47: error: expected ‘,’ before ‘)’ token
_Static_assert(sizeof(v) == sizeof(uint32_t));                 \
^
./lcfs-internal.h:77:47: error: expected ‘,’ before ‘)’ token
_Static_assert(sizeof(v) == sizeof(uint64_t));                 \
^
./lcfs-internal.h:83:47: error: expected ‘,’ before ‘)’ token
_Static_assert(sizeof(v) == sizeof(uint16_t));                 \
^
./lcfs-internal.h:95:47: error: expected ‘,’ before ‘)’ token
_Static_assert(sizeof(v) == sizeof(uint64_t));                 \
^
Fix it by adding error messages.
=> Fix compiler error

configure.ac, libcomposefs/Makefile-lib.am
This starts at 1.0.0 to signal incompatibilty with all previous (unstable) releases. At this point we strive to be ABI compat, and update the soname micro for non-api changes, and the minor for api additions.
=> Add soname for libcomposefs

tools/read-file.c
Revert any change to `errno` from a successful `fclose()`. According to [errno(3)](https://man7.org/linux/man-pages/man3/errno.3.html) a function that succeeds is allowed to change errno.
So it should be enough to
```diff
diff --git a/tools/read-file.c b/tools/read-file.c
index ee35a93..9d98663 100644
--- a/tools/read-file.c
+++ b/tools/read-file.c
@@ -118,15 +118,15 @@ char *read_file(const char *path, size_t *length)
buf = fread_file(f, length);
save_errno = errno;
if (fclose(f) != 0) {
if (buf) {
save_errno = errno;
free(buf);
}
errno = save_errno;
return NULL;
}
-
+       errno = save_errno
return buf;
}
```
I rearranged that code somewhat.
Does this PR make sense? (I'm not 100% sure)
=> read-file.c: restore errno after successful fclose()

libcomposefs/lcfs-internal.h, libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c
Some things were weirdly slow that really shouldn't, primarily related to the hash use. Here are some small fixes.
=> Some small performance fixes

libcomposefs/lcfs-mount.c
This is required on kernel >= 6.5 to handle escaped commas in upper or lowerdirs due to an overlayfs change in escape handling behaviour  caused by the switch to the new mount api internally.
For anything post 6.5 we fallback to the old legacy implementation which supports escaping.
This fixes https://github.com/containers/composefs/issues/213
=> Switch to new mount api for ovl on kernel 6.5 to fix escaping

tools/composefs-from-json.c
Musl uses readv/writev for stdio, so we need to allow them for the tests to pass.
Fixes #206
=> composefs-from-json; Include readv/writev in seccomp list

BSD-2-Clause.txt, COPYING.LESSERv3, COPYINGv3, LICENSE.Apache-2.0, Makefile.am, composefs.spec.in
As part of the Fedora package review, I ran scancode-toolkit to get proper SPDX codes. In doing so I saw that various licenses were referenced in the code but not included in the package. Those were
Apache-2.0 for composefs/tools/read-file.{c,h}
LGPL-3.0 for   composefs/libcomposefs/lcfs-fsverity.c
GPL-3.0 for composefs/tools/composefs-dump.c,
composefs/tools/composefs-from-json.c,
composefs/tools/composefs-info.c,
composefs/tools/mkcomposefs.c,
composefs/tools/mountcomposefs.c
There is some BSD 2 clause code included, but the code itself has the complete license included in it.
After adding the licenses, I made a first attempt at updating the spec file to include the appropriate SPDX lines as needed. This part may need further updates.
=> Add mentioned licenses to the code. Change spec to use SPDX

Makefile.am, composefs.spec.in, configure.ac
This allows avoiding the pandoc build dependency in downstream distributions (which is important for RHEL which does not provide pandoc) at the price of upstream developers requiring it.
The alternative would be to add the manpages to source control, so that pandoc would only be needed when modifying the markdown sources.
This is needed to remove the unwanted pandoc from the ELN buildroot while still providing man pages.
=> Use go-md2man for building manpages

composefs.spec.in
Only certain userspace libraries are still needed for compatibility on i686, and composefs is certainly not among them.
This is needed to fix the ELN build after #227, as golang (and hence go-md2man) are disabled there on i686.
=> Drop i686 from spec

README.md
Update [the link](https://erofs.docs.kernel.org) which contains more information about the latest status of EROFS although the website is still under construction for now.
Besides, the content of the old `.txt` one has been outdated for years since kernel documentation were switched into the reStructuredText format then.
=> Update EROFS documentation link

configure.ac
Changes since 1.0.1:
* Dropped composefs-from-json in tests in favour of using the composefs-info dump format.
* libyajl dependency dropped
* libcomposefs now limits the number of xattrs per file to 64k
* Fixed build against libc without reallocarray
* Performance fixes
* go-md2man is used instead of pandoc for manpages
* Minor fixes to spec file
=> Bump version to 1.0.2

composefs.spec.in
The cascade of packages which suddenly do not build on i686 due to the introduction of composefs as a dependency is causing issues.  Instead, allow this to be built without manpages.
This is a follow-up to #229.
/cc @cgwalters
=> Allow building without go-md2man

libcomposefs/lcfs-writer.c
Yet another picture perfect example of a bug that Wouldn't Happen In Rust.
Noticed by an internal static analyzer.
=> writer: Handle errors from `read`

libcomposefs/lcfs-mount.c, libcomposefs/lcfs-mount.h, tools/mountcomposefs.c
It turns out that the new append mechanism that was added in linux 6.5 that we used was disabled, and a new mechanism was added in 6.7. This changes the new-mount-api code to use the new approach.
Also, I added a "try verity" option that can be used for example by ostree to support fs-verity in an optional way to protect against accidental modification.  This can be passed in if you know fs-verity was enabled on the files, and will not fail if the kernel doesn't support the overlayfs verity= option. In comparison, for the signed usecase we must fail if verity is not supported.
=> Fix use of new mount API and add a try-verity mount option

tools/mkcomposefs.c
There is already a check here:
https://github.com/containers/composefs/blob/e63786d4c7e573f75c2db410b746521d11e7b105/tools/mkcomposefs.c#L246-L248
Adding such check in two other places.
=> mkcomposefs: Handle NULL from strndup()

README.md
README.md: Drop removed `signed` mount option
This doesn't exist anymore.
---
README.md: Fix markdownlint warnings
Nothing important, just clearing the warnings in my IDE.
---
=> `README.md`: Two patches

.github/workflows/test.yaml, configure.ac, hacking/installdeps.sh, libcomposefs/lcfs-mount.c
This aims to tackle https://github.com/containers/composefs/issues/252, i.e. allowing the build when macros MOUNT_ATTR_IDMAP and LOOP_CONFIGURE along with related structures are not available in the user API of the Linux kernel.
=> Support older linux headers

man/mkcomposefs.md
Whilst playing with mkcomposefs using small dummy files, it's confusing to find that objects are not created in the digest-store. There is an optimization to inline these files in the metadata (see lcfs-internal.h). Add a clarification to help.
=> man mkcomposefs: detail inlining logic

tools/cfs-fuse.c
I noticed this while reading the code.
=> fuse: Fix filepath argument in error message

man/mount.composefs.md
Just happened to notice the typo.
=> man/mount.composefs: Fix a typo and two markdown lint warnings

man/mount.composefs.md, tools/mkcomposefs.c, tools/mountcomposefs.c
Adding a few options that were missing
=> mountcomposefs, mkcomposefs: Add missing options to usage information

libcomposefs/lcfs-writer-erofs.c, tools/mkcomposefs.c
Check for errors in lcfs_node_set_content()  return value
=> erofs, mkcomposefs: Handle error from lcfs_node_set_content()

libcomposefs/lcfs-writer.c
According to [errno(3)](https://man7.org/linux/man-pages/man3/errno.3.html) a function that succeeds is allowed to change errno.
What if memdup() succeeds? 
I changed  the code to match how it's written here
https://github.com/containers/composefs/blob/d5ffbeb6844cdbe029f9c10cfa98239e2d6b1570/libcomposefs/lcfs-writer.c#L1472
=> writer: Set errno

libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c, tools/mkcomposefs.c
The interesting commit edits
tools/mkcomposefs.c
The other commit is just an attempt to reduce the number of source code lines.
=> handle NULL from lcfs_node_new() and move errno code into the function

libcomposefs/lcfs-writer-erofs.c
Adding checks for errors in  lcfs_build_node_from_image() return value.
(I marked this as a draft because I haven't traversed the different code paths yet)
=> erofs: Handle error from lcfs_build_node_from_image()

libcomposefs/lcfs-writer.c
A minor improvement:
Use EINVAL instead of ENOMEM if the format is not recognised
=> writer: Set errno for unknown format

tools/mountcomposefs.c
Fail with an error message if any of the
basedir option paths is an empty string.
=> mountcomposefs: Handle empty basedir option

libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, man/mkcomposefs.md, tools/mkcomposefs.c
This resolves #249 and results in 10x improvement for digest calculation and file copy.
Please refer the below document for details about the issue and the change. I would like to know your thoughts.
[threading.md](https://github.com/containers/composefs/files/14743119/threading.md)
=> Added multithreading support for mkcomposefs

libcomposefs/lcfs-utils.h, tools/mkcomposefs.c, tools/mountcomposefs.c
musl has removed the non-prototype declaration of basename from string.h which now results in build errors with newer clang compilers.
Implement GNU basename behavior using strchr which is portable across libcs.
Fixes:
| ../../git/tools/mountcomposefs.c:43:20:
| error: call to undeclared function 'basename'; ISO C99 and later do not | support implicit function declarations [-Wimplicit-function-declaration]
|    43 |         const char *bin = basename(argv0);
|       |                           ^
| ../../git/tools/mountcomposefs.c:43:14:
| error: incompatible integer to pointer conversion initializing 'const char *'
| with an expression of type 'int' [-Wint-conversion]
|    43 |         const char *bin = basename(argv0);
|       |                     ^     ~~~~~~~~~~~~~~~
For reference: …
=> musl: basename: use portable implementation for basename API

tools/mkcomposefs.c
This will be added when printing the error anyway.
=> mkcomposefs: Drop newline from error string

tools/mkcomposefs.c
This resolves #274 
Added fallback to classic file copy if the `copy_file_range` fails for the reasons it can be retried. I have tested the fallback with digest path set to a USB drive where the `copy_file_range` fails with `EXDEV`.
=> Added copy_file_range for faster file copy in mkcomposefs.

libcomposefs/lcfs-fsverity.c
This file uses htole64(), so it should define _GNU_SOURCE.
=> lcfs-fsverity: Add _GNU_SOURCE feature test define

libcomposefs/lcfs-internal.h, libcomposefs/lcfs-mount.c, libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, man/composefs-info.md, tests/test-lib.sh, tests/test-units.sh, tools/composefs-info.c, tools/mkcomposefs.c
Add API+CLI to get fsverity digests efficiently
- Add an API that first tries to ask the kernel for the fsverity
digest, and returns it if present, but otherwise does a fallback
to in-memory computation.  The primary use case here
is systems which want to canonically index files by their fsverity
digest (as opposed to e.g. sha256).  If the filesystem in the
future starts supporting fsverity (as e.g. XFS is slated to do)
then this allows an efficient in-place upgrade.
- Expose the measurement in the CLI.  `fsverity-utils` isn't
installed everywhere, and also today composefs makes hard decisions
(like using sha256) that that project doesn't do.
---
lib: Add a thin public API wrapper for `FS_IOC_ENABLE_VERITY`
The main thing is this helps …
=> lib: two new fsverity APIs

man/composefs-dump.md
It isn't, actually right now.  We could make it one but that would be a compat hazard, and it's just
easier to tell people to hex encode it.
=> man: Drop `=` as a special escaped character

.github/workflows/rust.yml, .gitignore, Cargo.toml, deny.toml, rust/src/dumpfile.rs, rust/src/lib.rs, rust/src/mkcomposefs.rs
Right now this includes just a parser/generator for dump files, which is helpful for e.g. a flow like taking a tarball, parsing it in Rust, and then serializing the entry to a composefs dumpfile line.
I'd like to add more opinionated and advanced functionality related to composefs implemented in this crate - *especially* integration with containers/OCI.  My thought is that in the short term we can publish this crate without having the core
C code depend on it.
I plan to use this crate in bootc.
However, more medium term, it may make sense to offer a CLI tool from this crate, in which case there will be some tension with the CLI tools that happen to be implemented in C, as commonly people would
=> Add a composefs Rust crate

configure.ac
I'd like to get out a release with at least the new overlayfs mount apis from linux 6.6 to avoid us falling back to legacy mount apis on newer kernels. But having the threaded mkcomposefs would be good too.
Also, we may want https://github.com/containers/composefs/pull/288 landed first
@cgwalters Does it make sense to dist the rust code?
Current release notes:
Changes since 1.0.4:
* Added LCFS_MOUNT_FLAGS_TRY_VERITY/tryverity mount option to do best-effort fs-verity
* Use the new loewerdir+ and datadir+ overlayfs mount options from linux 6.6
* mkcomposefs is now multi-threaded when computing digests and copying files
* mkcomposefs now uses copy_file_range when copying files
* Added some initial rust crates to handle composefs dump files
* Added fuzz tests
* Documentation updates
* Fix …
=> Bump version to 1.0.4 and lib version to 1.2.0

tests/test-units.sh
It was using `composefs-info` from the path, not the binary produced by the build.
`realpath` is required since the test changes the current directory, breaking the relative path it previously contained.
=> test: use correct `composefs-info` binary

.github/workflows/rust.yml, .github/workflows/test.yaml
Our current Rust CI was testing against the *stable* composefs, i.e. whatever happened to be in the current Fedora.
This is too confusing, so move the CI for Rust into the main workflow, and test against the C library under test too.
Also, add a `--all-features` run to add coverage for the feature that enables running against the latest C library.
=> ci: Test Rust code against current C code

tests/test-checksums.sh, tests/test-lib.sh, tests/test-random-fuse.sh, tests/test-units.sh
Just upstreaming some things I ran into while I was originally packaging for nixpkgs.
Since the builds happen in a minimal sandbox it was running into non-existing directories.
The only thing I'm not sure about is the tests that involve fsverity since usually `/tmp` is a `tmpfs` and might not support it. But in that case it is probably a better idea to specifically set `$TMPDIR` for those tests rather than hardcoding `/var/tmp`
=> test: remove hardcoded /tmp

README.md, rust/composefs-core/Cargo.toml, rust/composefs-sys/Cargo.toml
I want to publish `composefs-sys` but a `description` field is required, which is annoyingly not found by `cargo publish --dry-run`.
Do a few other tweaks while we're here, including talking about language bindings in `README.md`.
=> rust: Add mandatory `description` field, other misc changes

rust/composefs-core/Cargo.toml
This is unnecessary now that we switched to a workspace; I added the licenses as symlinks into each rust crate subdirectory to ensure they're included.  I verified we don't include the C code.
=> composefs-core: Drop incorrect `include`

.github/workflows/test-meson.yaml, hacking/installdeps.sh, libcomposefs/meson.build, man/meson.build, meson.build, meson_options.txt, tests/meson.build, tools/meson.build
This adds support for meson as an alternative build system to autotools.
=> Add meson as an alternative to autotools with corresponding CI

tests/test-units.sh, tools/composefs-info.c
`composefs-info --help` was segfaulting for me; missing an empty terminator struct. Did I mention yet this type of thing wouldn't happen in Rust?
=> info: Add missing terminator for `longopts`

libcomposefs/lcfs-mount.c
The "source" field for overlayfs isn't strictly meaningful, by default; but it's useful to identify at least the software that created the mount.
Motivated by https://gitlab.com/redhat/centos-stream/containers/bootc/-/issues/301 where some QE testing noticed that an updated composefs using the new mount API didn't specify the source at all, so it ends up as `none`, but if we fall back to the legacy one it uses `overlayfs`.
Change both to be `composefs`.
=> mount: Consistently use `composefs` as source

meson.build
Meson superprojects need to know which build target they should link with.
=> meson.build: Allow use as a meson subproject

tools/mkcomposefs.c
if the out_file is specified, make sure it is explicitly close()d and that possible errors are reported instead of being ignored.
=> mkcompose: report close() errors

libcomposefs/lcfs-writer.c
do not override the errno reported by the write_cb as we might lose useful errors like ENOSPC.
=> libcomposefs: do not override errno

libcomposefs/lcfs-mount.c
MS_RDONLY is enough to mount the image as read-only.
=> libcomposefs: drop using "ro" option

rust/composefs/src/dumpfile.rs, rust/composefs/src/lib.rs
rust: Drop unused cfg
Now checked by Rust 1.80, hooray.
---
dumpfile: Fix clippy lint
Use `matches!` for match-evaluating-to-bool.
---
=> Minor rust lints

.github/workflows/test.yaml, rust/composefs-sys/Cargo.toml, rust/composefs-sys/build.rs, rust/composefs/Cargo.toml
Copy over the pattern we have in ostree to add a feature that disables our build script (which pulls in a requirement on the libcomposefs C library, which doesn't exist in the docs.rs build env) when we detect we're being built on docs.rs.
=> rust: Attempt to fix build on docs.rs

libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, man/composefs-info.md, tests/meson.build, tests/test-dump-filtered.sh, tools/composefs-info.c
I'm looking at storing OCI container images with their metadata included in the image - giving a "single file" holding all the relevant bits for an image. Specifically a structure like this:
```
/manifest.json
/config.json
/rootfs
```
I want higher level tooling to be able to read the metadata efficiently. Of course we could directly parse the EROFS image...but a lot of pitfalls there. We could also mount the image but that's pretty inefficient for this.
Add support for filtering when generating a dump; this can operate fully unprivileged, and only requires some minor modifications to the library and CLI tooling.
=> dump: Support `--filter`

rust/composefs/Cargo.toml, rust/composefs/src/dumpfile.rs, rust/composefs/src/mkcomposefs.rs
This allows us to deserialize from a composefs file.
=> rust: Add wrapping for composefs-info dump

.github/workflows/test.yaml, tests/test-units.sh
Primarily this fixes #324 , but there are also some cleanup and other fixes.
=> Various fixes to the fsverity part of test-units.sh

libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, tools/composefs-info.c, tools/mkcomposefs.c
I stumbled across the fact that on Linux/glibc at least `dev_t` is 64 bits, but we were truncating it to 32 bits.
Note that the type used in the `mkcomposefs` binary was already uint64_t but because C happily truncates/converts integers this was missed.
=> Add 64bit rdev APIs

libcomposefs/lcfs-mount.c
When attempting to read the header of the erofs file before mounting it, we verify that the read is successful, but not that the full header has been returned.  We then proceed to access the header, which means we could be reading uninitialized memory.
Add a check to verify that we've read the full header.  If not, return -EINVAL, which is what we already return in case the header was incorrect.
=> libcomposefs: detect short erofs files

rust/composefs/src/dumpfile.rs
Pairs with https://github.com/containers/composefs/pull/329 which adapts the C side to properly accept these too.
This breaks semver, we'll need to bump that.
=> rust: Accept 64 bit values for rdev

libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, tools/mkcomposefs.c
mkcomposefs: Drop duplicate invocation of lcfs_node_set_mode()
Just noticed this while I was reading the code for other reasons.
---
Add fallible lcfs_node_try_set_mode()
Previously I added code to validate this but it happened much
later. The mode (type) of a file is a very fundamental property
and we should constrain its state as early as possible.
---
Add lcfs_node_set_symlink_payload
Historically we accept any arbitrary data in the dumpfile
for the file size for symlink, and end up ignoring it
ultimately when we write the EROFS. However previously
it was pretty confusing as the in-memory node data
could have a bogus size.
Add an API and use it both in the mkcomposefs path *and*
in the …
=> A few cleanups around symlinks

tests/test-checksums.sh
When testing out changes to a dumpfile, today the sha check will always fail first if I don't go and change the expected value, but most of the time what I want to know is whether or not it passes the *other* tests at least.
Move the checksum verification last, and also while we're here print an "ok" value.
=> tests: Move sha verification after other checks

.github/workflows/test.yaml
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Looks like this has outright started failing now, see:
https://github.com/containers/composefs/actions/runs/10793804365/job/29936602526#step:1:24
https://github.com/containers/composefs/actions/runs/10793804365/job/29936603900#step:1:24
Signed-off-by: John Eckersberg <jeckersb@redhat.com>
=> ci: update deprecated {up,down}load-artifact@v2 to v4

rust/composefs/examples/cfs-dumpfile2tar.rs, rust/composefs/src/dumpfile.rs
Add code to go from dumpfile -> tar (notably, ignoring non-inline regular file content). This is *testing* only code right now, though clearly mapping to/from tar would be very useful in general. I plan to use this code for various testing purposes especially to *manually* create tarballs from various dumpfiles to e.g. feed directly to `mkfs.erofs` for example.
But we at least get some sanity checking this way.
=> dumpfile: Add some test code to convert to tar

tests/test-checksums.sh, tools/mkcomposefs.c
Right now in some cases we have "loose" semantics; a simple case I noticed earlier is we accepted whatever input size for a symlink but ignored it.
I also noticed we accepted (and ignored) a nonzero rdev for a non-device.
We have prior cases around missing trailing newline, etc.
In preparation for a more official "mkcomposefs --strict" mode, add a hidden environment variable and use it to validate some of the above.
There's other bits missing though - for example in strict mode I'd like to hard require that the xattrs are already in canonical form (sorted, no duplicates).
This touches on a general topic that there's "strict" and then something even stronger around "normal form" where we disallow any ambiguous input such as duplicate `//` in filenames etc.
That'd be a good bit more work. …
=> mkcomposefs: Add a hidden CFS_PARSE_STRICT

.clang-format-include, libcomposefs/lcfs-internal.h, libcomposefs/lcfs-writer-erofs.c, libcomposefs/lcfs-writer.c, tests/meson.build, tests/test-lcfs.c
Unfortunately at least ostree does:
node = lcfs_node_new()
lcfs_node_add_child(parent, node);
lcfs_node_set_mode(node, ...)
So we basically have a completely uninitialized node as part of the tree.
This failed our basic "validate the mode" logic.
We can't do any validation at all in `lcfs_node_add_child()` so move it to the first time we walk the tree as part of `lcfs_node_write_to()`.
Also as part of fixing this: Today we don't really have coverage of the C library as it may be used by external consumers. Add a unit test to verify this, and we can build on this more.
=> lib: Move validation out of lcfs_node_add_child()

libcomposefs/lcfs-writer-erofs.c
- Followup from review comments to clarify how this works
- Rename the function to further reinforce it's not "empty" it's actually the special null addr
- Actually use the `EROFS_NULL_ADDR` constant when we do the writing to make the connection more obvious
- When reading back an erofs, at least verify that it's chunk based as extra validation.
=> writer: Clarifications around our usage of EROFS_NULL_ADDR

rust/composefs-sys/Cargo.toml, rust/composefs-sys/build.rs, rust/composefs/Cargo.toml
The build on docs.rs is still failing due to missing the C library. The standard thing to do here is just not to look for it when building docs.
This time I copied the setup from gtk4-rs; the newer pattern here seems to be directly using `rustc-args` and `rustdoc-args` instead of exposing a `dox` feature.
What I believe I missed in the last attempt was the copy of `package.metadata.docs.rs` in the `composefs`
crate.
=> rust: Another attempt to fix docs.rs build

tools/mkcomposefs.c
A tiny improvement that I've noticed while looking at the code.
use sched_getaffinity to get the CPUs that can be used.
=> mkcomposefs: make it cpuset aware

rust/composefs-sys/src/lib.rs, rust/composefs/src/fsverity.rs
On the C side we have two functions:
- `lcfs_compute_fsverity_from_fd`
- `lfs_fd_get_fsverity`
The first is currently defined to operate purely in memory. The second checks if fsverity is already enabled on the fd, and if so just asks the kernel for it; falling back to the first case otherwise.
I'm actually not entirely sure if we really need both; it seems like if we have a fd we'd basically always want to use the kernel code if possible.
Out of conservatism for now, expose both on the composefs-sys Rust binding side. But on the high level interface just change what we're using to be backed by `lcfs_fd_get_fsverity()`.
If someone really cares later of course we can add sugar for the pure compute path in the high level Rust API too.
=> Expose optimized fsverity interface to Rust

composefs.spec.in
I really don't like maintaining spec files upstream but whatever, not a battle I am likely to win in
the near future.
=> spec: Sync from Fedora

man/mkcomposefs.md
Alternative to https://github.com/containers/composefs/pull/358 which would have put some internal sandboxing.
=> mkcomposefs: Document external sandboxing

meson.build
Some C11 features have been used, but meson.build still specifies c_std=c99, leading to errors on Clang compiler.
Fixes: https://github.com/containers/composefs/issues/364
=> meson.build: raise used C standard to C11

libcomposefs/lcfs-writer.c
XATTR_NAME_MAX is defined in linux/limits.h, but leaked by glibc since its sys/param.h includes the former header, which is not true on musl and leads to errors like:
```
../libcomposefs/lcfs-writer.c:1688:16: error: use of undeclared identifier 'XATTR_NAME_MAX'
1688 |         if (namelen > XATTR_NAME_MAX) {
```
Include linux/limits.h explicitly to build properly on musl.
=> libcomposefs: include linux/limits.h to satisfy usage of XATTR_NAME_MAX

.github/workflows/test.yaml, rust/composefs/Cargo.toml
It's been out long enough I think we can do this.
Motivated by wanting to write some code using
it in an example and it's apparently not possible
to use off-by-default features in examples.
=> rust: Enable v1_0_4 feature by default

.github/workflows/test.yaml, libcomposefs/lcfs-mount.c, libcomposefs/lcfs-writer.c, tools/composefs-info.c, tools/mkcomposefs.c
Followup to https://github.com/containers/composefs/pull/365
=> Fix clang warnings

libcomposefs/lcfs-utils.c, libcomposefs/lcfs-utils.h, libcomposefs/meson.build, tools/composefs-info.c, tools/meson.build, tools/mkcomposefs.c
I came across the fact that we had two copy-paste implementations
of converting a binary digest to hex.
Deduplicate with an internal shared library.
NOTE: I don't speak meson fluently so please check if I messed
something up there.
=> Add a libcomposefs-internal

libcomposefs/lcfs-internal.h, libcomposefs/lcfs-writer-erofs.c
The real motivation here is to rewrite the code in order to complete the relicensing, because the person who last touched this didn't respond.
And in general, using `_Generic` here cleans things up anyways.
=> internal: Rewrite byteswapping macros

.github/workflows/test.yaml, tests/integration.sh
integration: Clearly show in logs if we tested with fsverity
---
tests: Add a flow for integration test with fsverity enabled
This was an obvious CI coverage gap.
---
=> tests: Add a flow for integration test with fsverity enabled

README.md
Folks were understandably unaware of the matrix channel.
=> README.md: Link to community forums

MAINTAINERS.md
This list is intentionally a strawman proposal; I listed the current 4 top contributors (as computed by GH).
It obviously overlaps with the GH commit access, but that's something tools exist to synchronize.
Motivated by matching community standards.
=> MAINTAINERS.md: New file

.github/workflows/test.yaml
It looks like some of the images went away, update the
version and use Debian.
=> ci: Update run-on-arch

libcomposefs/lcfs-writer.c
It probably does not make much difference but for clarity add the flag `O_DIRECTORY`
=> writer: Add O_DIRECTORY

.github/workflows/test.yaml, libcomposefs/lcfs-mount.c, libcomposefs/lcfs-writer.c, libcomposefs/lcfs-writer.h, tests/test-lcfs.c
lib: Add lcfs_fd_measure_fsverity
Our history with fsverity APIs is a bit messy. For now historical
reasons lcfs_fd_get_fsverity tries to query the kernel (via ioctl)
but will silently fall back to userspace computation - which
is sometimes desirable, other times not.
We also have lcfs_fd_compute_fsverity which is unconditionally
userspace.
However some cases actually really want to require the
fd to have fsverity - so add an API to do that.
---
writer: Canonicalize no-verity errno to -ENOVERITY
This is what we do elsewhere.
---
lib/mount: Use lcfs_fd_measure_fsverity
This is ensuring we have our fsverity ioctl parsing code in
one place.
--- …
=> lib: Add lcfs_fd_measure_fsverity

composefs.spec.in
On arches like i686 the build of composefs fails because go-md2man is not available. The failure is caused by man page generation is enabled unconditionally.
=> Do not enable man page generation when it is disabled.

libcomposefs/lcfs-writer.c, tests/test-lcfs.c
Since the first creation of this code in
5ac1f5c4 "lib: Update xattr APIs" this function
has always returned an error code - but nothing
checked it, so it didn't matter.
Now also, currently this function cannot fail
but let's give ourselves some flexibility here;
perhaps we want to e.g. invoke `realloc`
and in that case we'd need to handle OOM.
I just noticed this while working on commit
02077e89b5b81c76e962a6643c7a7423b1f8336f
to reject empty xattr names.
Change this to return success, and also check its
return value in the set path.
=> writer: Fix return value of lcfs_node_unset_xattr

.github/workflows/builds.yaml, hacking/installdeps.sh
Targeting a few distributions, produce a tarball with binaries.
This is intended to be used in other downstream CI scenarios.
=> Add release binaries from git main on push

libcomposefs/lcfs-mount.c
It turns out we can directly mount `/dev/fd/$fd`, so current API does not need to be changed.
Closes: #361
Closes: https://github.com/containers/composefs/issues/144
=> mount: Support EROFS file-backed mounts

tools/mkcomposefs.c
`failed_path` is declared here:
https://github.com/containers/composefs/blob/14ad6b9c8447dc57113028ffda65d9bfcb2c3cdd/tools/mkcomposefs.c#L1508
It looks like `failed_path` has not been set when it's used here:
https://github.com/containers/composefs/blob/14ad6b9c8447dc57113028ffda65d9bfcb2c3cdd/tools/mkcomposefs.c#L1672
An alternative fix is to use `src_path`. 
I just took the easiest alternative and removed the argument, but I can change that if you want.
=> mkcomposefs: Fix error message

README.md
The in-tree crates are gone now.
=> README: Link to composefs-rs

tests/meson.build
Meson applies a default timeout of 30 seconds to all tests ([source](https://mesonbuild.com/Unit-tests.html#other-test-options%3E)). Since the check-checksums test is quite I/O-heavy, this might lead to timeouts in CI builds depending on the load of the build machines. Increase it to 300 seconds (same as check-random-fuse) to be on the safe side.
=> tests: increase check-checksums timeout to 300 seconds

man/composefs-dump.md, man/composefs-info.md, man/meson.build, man/mkcomposefs.md, man/mount.composefs.md
While packaging for Debian, lintian complained about the section headers:
```
W: composefs: wrong-manual-section 1 != composefs [usr/share/man/man1/composefs-info.1.gz:2]
W: composefs: wrong-manual-section 1 != composefs [usr/share/man/man1/mkcomposefs.1.gz:2]
W: composefs: wrong-manual-section 1 != composefs [usr/share/man/man1/mount.composefs.1.gz:2]
W: composefs: wrong-manual-section 5 != composefs [usr/share/man/man5/composefs-dump.5.gz:2]
```
(See <https://lintian.debian.org/tags/wrong-manual-section.html> for full info about the warning.)
According to man-pages(7), the .TH syntax is:
```
.TH title section date source manual-section
```
Remove the parentheses so that the section is detected correctly, leave the date empty, and escape the space in the last argument to comform to the …
=> man: fix section headers

tests/test-units.sh
When executing the tests in a sandbox, this is the error we get when running on a kernel with fsverity support, but sandbox restrictions preventing us from mounting something.
I failed to understand why this occurred the first time with v1.0.8.
=> tests: ignore EOPNOTSUPP in in fsverity tests

tools/mkcomposefs.c
`lcfs_build()` might have set `failed_path` to `NULL`. This could happen if `maybe_join_path()` returns `NULL` due to a `malloc()` failure. If this happens, use an empty string to avoid segfaulting in `err()`.
I spotted this when I was reading the code. I hope the analysis is correct. I think it's better to use the somewhat confusing error message `error accessing` than seqfaulting.
=> mkcomposefs: handle failed_path NULL from lcfs_build()
