- fuzzing/main.c
- kernel/cfs.c
- kernel/lcfs-fuzzing.h
- kernel/lcfs-reader.c
- kernel/lcfs-reader.h
adjust fuzzing tests to the new API.
> fuzzing: fix tests

- README.md
- composefs.cli
> Add documentation for how to use selinux with composefs

- fuzzing/Makefile
- fuzzing/main.c
- kernel/lcfs-fuzzing.h
- kernel/lcfs-reader.c
- kernel/lcfs-verity.h
> test: fix fuzzing

- fuzzing/main.c
- kernel/lcfs-reader.h
> fuzzing: test new APIs

- kernel/cfs.c
> cfs: Remove unused variable

- fuzzing/Makefile
- fuzzing/main.c
- kernel/lcfs-reader.h
> fuzzing: more improvements

- fuzzing/main.c
- kernel/cfs.c
- kernel/lcfs-reader.c
- kernel/lcfs-reader.h
- kernel/lcfs.h
- libcomposefs/lcfs-writer.c
- libcomposefs/lcfs.h
- tools/dump.c
> src: drop types definition for lcfs_off_t and lcfs_c_str_t

- libcomposefs/lcfs-writer.c
> lcfs-writer: Remove unused variable

- hacking/.clang-format
- hacking/Makefile
- kernel/cfs.c
- kernel/lcfs-fuzzing.h
- kernel/lcfs-reader.c
- kernel/lcfs-reader.h
- kernel/lcfs-verity.h
- kernel/lcfs.h
- libcomposefs/lcfs-writer.c
- libcomposefs/lcfs-writer.h
- libcomposefs/lcfs.h
- tools/dump.c
- tools/mkcomposefs.c
- tools/writer-json.c
> src: format with clang-format

- kernel/cfs.c
allow to specify multiple basedirs -o basedir=/path1:/path2 where
files are looked up sequentilly in a similar way to what overlayfs
does.
> kernel: allow multiple basedirs

- kernel/cfs-verity.h
> build: run clang-format

- fuzzing/main.c
- kernel/Documentation/filesystems/composefs.rst
- kernel/cfs-fuzzing.h
- kernel/cfs-reader.c
- kernel/cfs-reader.h
- kernel/cfs-verity.h
- kernel/cfs.c
- kernel/cfs.h
These are some fixes from review of the kernel patchset.
> Minor changes from review feedback

- kernel/cfs-reader.c
- kernel/cfs.c
- kernel/cfs.h
Sort includes and remove unused includes.
> kernel: Clean up includes

- kernel/cfs-internals.h
- kernel/cfs-reader.c
- kernel/cfs.c
Amongs other things this gets us mostly clean with checkpatch --strict
> Various cleanups

- kernel/cfs.c
This retargets statfs() to the first base directory so that we get at least some size info. Free space isn't super important as the fs is not writable, but it makes sense to have at least some value to avoid confusing apps thinging the disk is full.
Fixes https://github.com/containers/composefs/issues/18
> kernel: Implement statfs()

- kernel/cfs.c
This uses private mounts for the basedirs and do lookup in those. This means the opens in those will never access mounts that are mounted after the mount of the composefs itself, and thus we will never get loops.
> Avoid loops when opening basedir files

- kernel/cfs.c
> kernel: Remove unused variable rootpath

- kernel/cfs-reader.c
- kernel/cfs.c
See the kernel robot responses in:
https://lore.kernel.org/lkml/cover.1669631086.git.alexl@redhat.com/
> Fix reports from kernel test robot

- kernel/Documentation/filesystems/composefs.rst
Applied feedback from Bagas Sanjaya <bagasdotme@gmail.com> in: https://lore.kernel.org/lkml/Y4YSYcqv3LdbseVy@debian.me/
> kernel: Fix documentation

- tools/mkcomposefs.c
use a dynamic allocation for file paths instead of reusing the same static buffer.
Closes: https://github.com/containers/composefs/issues/81
> mkcomposefs: dynamically allocate paths

- README.md
- kernel/Documentation/filesystems/composefs.rst
- kernel/cfs-reader.c
- libcomposefs/lcfs-writer.c
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>
> Fix documentation typos

- hacking/clang-format/.clang-format
- kernel/cfs-internals.h
- kernel/cfs-reader.c
- kernel/cfs.c
- kernel/cfs.h
- libcomposefs/lcfs-fsverity.c
- libcomposefs/lcfs-fsverity.h
- libcomposefs/lcfs-writer.c
- libcomposefs/lcfs-writer.h
- libcomposefs/lcfs.h
- tools/dump.c
- tools/mkcomposefs.c
- tools/read-file.c
- tools/writer-json.c
This is mainly based on feedback from @masneyb, but also fixes some recently added checkpatch.pl reports.
> Various fixes based on kernel list feedback

- kernel/Documentation/filesystems/composefs.rst
> Update kernel docs based on feedback from Bagas Sanjaya on the list

- kernel/cfs-internals.h
- kernel/cfs-reader.c
- kernel/cfs.c
two minor nits that were noticed while debugging another problem.
> two minor cleanups

- kernel/cfs.c
> kernel: Make cfs_parameters static

- kernel/cfs.c
If any base dir is specified our stack depth is the maximum basedir stack depth plus one, which should never surpass
FILESYSTEM_MAX_STACK_DEPTH.
> kernel: Compute and check stack depth

- COPYING
- COPYING.LIB
- Makefile.am
- composefs.pc.in
- composefs.spec.in
- configure.ac
- libcomposefs/Makefile-lib.am
- libcomposefs/hash.c
- libcomposefs/hash.h
- libcomposefs/lcfs-cfs.h
- libcomposefs/lcfs-erofs.h
- libcomposefs/lcfs-fsverity.c
- libcomposefs/lcfs-fsverity.h
- libcomposefs/lcfs-internal.h
- libcomposefs/lcfs-mount.c
- libcomposefs/lcfs-mount.h
- libcomposefs/lcfs-utils.h
- libcomposefs/lcfs-writer-cfs.c
- libcomposefs/lcfs-writer-erofs.c
- libcomposefs/lcfs-writer.c
- libcomposefs/lcfs-writer.h
* Relicense lib to LGPL
* Fix make dist
* Add spec file
* Add pkg-config file
> Various packaging and distribution fixes

- libcomposefs/lcfs-mount.c
- libcomposefs/lcfs-writer-cfs.c
- libcomposefs/lcfs-writer-erofs.c
- libcomposefs/lcfs-writer.c
- libcomposefs/lcfs-writer.h
- tools/dump.c
- tools/mkcomposefs.c
- tools/writer-json.c
the only breaking change is for `lcfs_build`
> a bunch of warnings fixes

- libcomposefs/lcfs-writer.c
This results in *significantly* less duplicate code in this function.
> writer: Use cleanup attributes

- tools/mkcomposefs.c
This makes generating an object store a lot more efficient if available; one can construct a filesystem tree however, run `mkcomposefs --digest-store=` on it, and if the digest store and the source tree are on the same filesystem, then we get O(1) copies.
One interesting twist with this is the intersection of reflinks and fsverity; the only Linux filesystem supporting both today is btrfs, and I gave this a quick test there and it seems to work. (There are pending xfs patches for fsverity which would also
enable this there)
> mkcomposefs: Use FICLONE if available for objects

- libcomposefs/lcfs-utils.h
- tools/mkcomposefs.c
Just an ongoing effort to use the cleanup attribute.
> mkcomposefs: Use cleanup_fd

- libcomposefs/lcfs-writer.c
lib: Use common function to remove all children
Prep for further cleanup.
---
lib: Avoid O(N^2) behavior on cleanup
This library was written in a very general way with an API
`lcfs_node_remove_child` that required removing an arbitrary
member of the children array.  I found a bug in that code
previously in that it should have been using `memmove`, not
`memcpy`.
However, I think there's no need for us to support arbitrary
tree computations.
Today at process exit we walk over the in-memory filesystem
and we end up with an O(N^2) behavior because we keep removing
the first child.
Instead, because we *only* need to care about removing all
children at once, just iterate over them and then free them
as we go.
Note: I only noticed this code …
> lib: Avoid O(N^2) behavior on cleanup

- libcomposefs/lcfs-writer-erofs.c
In the v4 patch series, the digest xattr is replaced with a versioned data header for the old metacopy xattr, with an optional digest.
> Update to new xattr format using metacopy xattr for digest

- README.md
I modified
"_shared files need only be stored once_"
Please correct me if I'm wrong. (My first language isn't English)
> README.md: Fix typos and language

- tools/cfs-fuse.c
- tools/composefs-from-json.c
Got this when building the rpm on f38
> Fix some warnings

- .github/workflows/test.yaml
> ci: Run apt update

- libcomposefs/lcfs-mount.c
Found by clang-analyzer.  This one is really a textbook example of why the cleanup attribute solves so many bugs.
> mount: Fix memory leak in error path

- composefs.spec.in
- Take in fixes from reviwers to fix man page compression types
- Take in fixes from reviwers to move licenses to lib subpackage
> Start collecting Fedora review fixes

- libcomposefs/lcfs-writer.c
We're hitting this child lookup a lot when inserting file due to the check for existing files in add_child(), and then doubling this when cloning the tree in the writer.
So, this makes lcfs_node_add_child() guarantee that children are sorted always, which means we can use a binary seach for all lookups, and we can avoid the qsort when canonicalizing images.
This speeds up mkcomposefs on a large --from-file image from 790 msec to 470 msec.
> lib: Keep children sorted and lookup using binary search

- .github/workflows/test.yaml
- tests/fuzzing/run.sh
Closes: https://github.com/containers/composefs/issues/241
> .github: run make distcheck as part of the CI

- libcomposefs/lcfs-writer.c
> writer: Close mmap leak

- libcomposefs/lcfs-writer-erofs.c
- libcomposefs/lcfs-writer.c
> lib: Add missing lcfs_node_unref()

- rust/composefs-core/Cargo.toml
- rust/composefs-core/src/fsverity.rs
- rust/composefs-core/src/lib.rs
Prep for a first publishing of the crates.
> rust: Some doc and misc tweaks

- configure.ac
- meson.build
A lot of changes since the last release, time to do a new one!
I bumped the lib version minor since we have added new APIs.
> Release 1.0.5

- rust/composefs/src/dumpfile.rs
Trivial optimization: I just realized that we can detect the case when the input is already canonical and return a borrowed version.
> rust/dumpfile: Minor optimization for unescape_to_path_canonical

- rust/composefs/src/dumpfile.rs
dumpfile: Limit max inline content
Corresponding to what we did on the C side.
(Yeah, if we grow more of this we can try to use bindgen
to share constants)
This I'm pretty sure is the last section of thing that accepted
arbitrarily sized data.
---
dumpfile: Deny content being set for non-regfiles
Just additional validation.
---
> two more rust dumpfile parser hardenings

- rust/composefs-sys/Cargo.toml
- rust/composefs/Cargo.toml
> rust: Release 0.1.1

- rust/composefs/src/dumpfile.rs
- Ensure that only regular files can have content or fsverity digest
- Ensure that only devices can have nonzero rdev
> rust/dumpfile: Add more validation

- libcomposefs/lcfs-fsverity.c
- libcomposefs/lcfs-internal.h
- libcomposefs/lcfs-writer.c
> writer: Use blocksize constant

- libcomposefs/lcfs-internal.h
Tracing through these xattrs, I found it helpful to have comments with the expansion.
> lib: Add expansion comments to header

- meson.build
Nothing *large* here, a collection of build system bits, CI fixes, style fixes, and one cpuset change for mkcomposefs.
> Release 1.0.7

- CODE-OF-CONDUCT.md
Added COC file that redirects to Containers org COC.
> Add Containers Code of Conduct

- rust/composefs-sys/Cargo.toml
- rust/composefs/Cargo.toml
> rust: release 0.1.3

- meson.build
A new year, time to do a new release!
> Release 1.0.8
